name: Publish LB images

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Set up Docker Buildx
        id: build_lb
        uses: docker/setup-buildx-action@v1
      
      - name: Build and push nginx1
        id: docker_build1
        uses: docker/build-push-action@v2
        with:
          context: ./nginx1
          file: ./nginx1/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/lb_nginx1:1.0

      - name: Build and push nginx2
        id: docker_build2
        uses: docker/build-push-action@v2
        with:
          context: ./nginx2
          file: ./nginx2/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/lb_nginx2:1.0

      - name: Build and push haproxy
        id: docker_build3
        uses: docker/build-push-action@v2
        with:
          context: ./ha_proxy
          file: ./ha_proxy/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/lb_haproxy:1.0
